use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMDataCenter_Example' do
  pod 'AHFMDataCenter', :path => '../'

  target 'AHFMDataCenter_Tests' do
    inherit! :search_paths

    
  end
end
